USE [master]
GO

/****** Object:  Database [Flights_Management]    Script Date: 12/25/2012 21:07:18 ******/
CREATE DATABASE [Flights_Management] ON  PRIMARY 
( NAME = N'Flights_Management', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Flights_Management.mdf' , SIZE = 3072KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Flights_Management_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL10_50.MSSQLSERVER\MSSQL\DATA\Flights_Management_log.ldf' , SIZE = 8384KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Flights_Management] SET COMPATIBILITY_LEVEL = 100
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Flights_Management].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Flights_Management] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Flights_Management] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Flights_Management] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Flights_Management] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Flights_Management] SET ARITHABORT OFF 
GO

ALTER DATABASE [Flights_Management] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Flights_Management] SET AUTO_CREATE_STATISTICS ON 
GO

ALTER DATABASE [Flights_Management] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Flights_Management] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Flights_Management] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Flights_Management] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Flights_Management] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Flights_Management] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Flights_Management] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Flights_Management] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Flights_Management] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Flights_Management] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Flights_Management] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Flights_Management] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Flights_Management] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Flights_Management] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Flights_Management] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Flights_Management] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Flights_Management] SET  READ_WRITE 
GO

ALTER DATABASE [Flights_Management] SET RECOVERY FULL 
GO

ALTER DATABASE [Flights_Management] SET  MULTI_USER 
GO

ALTER DATABASE [Flights_Management] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Flights_Management] SET DB_CHAINING OFF 
GO

